### ISSUE TITLE
Remote support?

### ISSUE THREAD

**Issue by xaviervv** [SharpeRAD/Cake.Topshelf#10]
Hi,
I couldn't find anything in the repo or documentation about remote support. 
Should I be using cake.services instead? Even if my application is TopShelf based?
The only other way around this would be to use a remote connection and call the exe myself I suppose?

**Comment by SharpeRAD** [comment]
Yes once your windows service has been installed you can control it via Cake.Services. The TopShelf library doesn't provide any remote support directly.
