### ISSUE TITLE
Could not use version 0.2.1 with Cake 0.26.0

### ISSUE THREAD

**Issue by sky-claudiacrisostomo** [SharpeRAD/Cake.Topshelf#11]
Using the cake version 0.26.0 with Cake.Topshelf 0.2.1, the lib doesn't work.

`
Error: The assembly 'Cake.Topshelf, Version=0.2.1.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.22.0).
This assembly need to reference at least Cake.Core version 0.26.0.
Another option is to downgrade Cake to an earlier version.
It's not recommended, but you can explicitly opt-out of assembly verification
by configuring the Skip Verification setting to true
(i.e. command line parameter "--settings_skipverification=true",
environment variable "CAKE_SETTINGS_SKIPVERIFICATION=true",
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)
`

Can you give me, access to solve this issue?

**Comment by SharpeRAD** [comment]
Resolved in v0.2.2
