### ISSUE TITLE
displayname, description and servicename should use a single dash when specified as arguments. TopShelf install fails otherwise

### ISSUE THREAD

**Issue by AdrianLogan** [SharpeRAD/Cake.Topshelf#6]
Currently InstallArgumentsFactory is specifying '--' in front of the following arguments:
- servicename  
- displayname
- description

This is causing the TopShelf install to fail with"Topshelf.HostConfigurationException: The service was not properly configured".  
 
The TopShelf [command line](http://docs.topshelf-project.com/en/latest/overview/commandline.html) documentation states that these parameters should only have a single dash.

**Comment by SharpeRAD** [comment]
Fixed in v0.09
