### ISSUE TITLE
Exception during install is not stopping the cake script or reporting the error

### ISSUE THREAD

**Issue by AdrianLogan** [SharpeRAD/Cake.Topshelf#7]
In the TopShelf install fails i.e. as in issue #6, the error is not propagated to CakeBuild so the script does not stop. 

As can be seen in the following image the install is reported as successful by CakeBulld  
![image](https://user-images.githubusercontent.com/723206/27962928-a47a145c-6333-11e7-8c03-d4dd5b577ada.png). 
But this did not install due to the invalid arguments, as noted in #6. 

If the TopShelf command is run directly from the command line (as recorded by running the cake script with Diagnostic output) the following error actually occurred: 
![image](https://user-images.githubusercontent.com/723206/27963182-815605b6-6334-11e7-8b82-a59985714594.png)

**Comment by AdrianLogan** [comment]
In order to have TopShelf return a exit coce you have to do it yourself. Something along the lines of [TopShelf Exit Code Guidance](https://github.com/MRCollective/DotNETContinuousDeploymentScripts/issues/1).

But the return code is not getting checked when starting the [Runner](https://github.com/SharpeRAD/Cake.Topshelf/blob/master/src/Topshelf/Manager/TopshelfManager.cs#L70) so the cake process does not abort

**Comment by SharpeRAD** [comment]
Closed, inline with your deleted comment. If you feel it is an issue then submit a PR to resolve it.
