### ISSUE TITLE
Start & Stop are missing -instance option

### ISSUE THREAD

**Issue by wojciechrak** [SharpeRAD/Cake.Topshelf#8]
Using `StartTopshelf` and `StopTopshelf` aliases with instance parameter works incorrectly.
Arguments supplied to .exe are respectively 

    start {instance}
    stop {instance}

when according to Topshelf CLI reference (https://topshelf.readthedocs.io/en/latest/overview/commandline.html) they should be 

    start -instance {instance}
    stop -instance {instance}

**Comment by SharpeRAD** [comment]
Good catch, i've added them in v0.2.1 👍
