### ISSUE TITLE
InstallTopshelf fails to install service but indicates success

### ISSUE THREAD

**Issue by wojciechrak** [SharpeRAD/Cake.Topshelf#9]
This one is a bit weird.

I am installing my Topshelf service like this:

```
var topshelfSettings = new TopshelfSettings { Instance = "A" }l
InstallTopshelf(execPath, topshelfSettings);
```

When this is run, I get `Topshelf service installed.` message.

However it's not present in services.msc. Also there is no regular Topshelf output like

```
Running a transacted installation.

Beginning the Install phase of the installation.
Installing service MyService$A...
Service MyService$Ahas been successfully installed.

The Install phase completed successfully, and the Commit phase is beginning.

The Commit phase completed successfully.

The transacted install has completed.
```

I've tried to debug this and strange thing - with debugger attached all works fine.
So I've added printing Exit code from the process, and it returns -1, but ErrorOutput is empty.

I run my cake script from elevated Powershell prompt.

**Comment by SharpeRAD** [comment]
Sorry but this will be an issue with your Topshelf service not the addin calling it.

**Comment by wojciechrak** [comment]
I am not sure, since it works when I invoke the same commands directly from the script (with `StartProcess()`).
